### ISSUE TITLE
Retain cycle

### ISSUE THREAD

**Issue by alsoft-alex** [tgebarowski/SwiftBehaviors#1]
Hi Tomasz,

There is currently a problem related to the fact that the behavior uses a strong pointer to its owner. Because a behavior is already pointed to (strongly) by its owner (via the associated object), it creates a retain cycle. In result the owner will never be released.

Please use a weak variable for the _owner ivar and owner property.

BR,
Aleksander Palka

**Comment by tgebarowski** [comment]
Hi Aleksander,

Thanks for tracking down the issue. I will fix it soon.

Cheers,
Tomasz

**Comment by tgebarowski** [comment]
Should be fixed in: https://github.com/tgebarowski/SwiftBehaviors/commit/0e894922b8ce7f7a36edbcbb6aae7d53b7342754

**Comment by alsoft-alex** [comment]
Thanks!
